### ISSUE TITLE
datasetutils is unable to determine the delimiter correctly

### ISSUE THREAD

**Issue by ktokarski** [forcedotcom/Analytics-Cloud-Dataset-Utils#11]
Hey, 
I am trying to upload the new dataset ( *.csv) into the Wave with use of datasetutils-32.0.27 but I receive the error message that the jar is not able to recognize the delimiter, even though it has ",".

The error log says that "File ... has delimiter { }"

Could you advise on this?

Many thanks in advance!

**Comment by ktokarski** [comment]
Any ideas on this?

**Comment by datasetutil** [comment]
do you only have a few lines in your input csv?

**Comment by ktokarski** [comment]
The file contains at least monthly data, so few thousands of lines.

**Comment by tbacewicz** [comment]
@ktokarski Any way you could provide a few lines of your CSV for us to look at? Hard to debug without seeing the actual data.

**Comment by gtsntzs** [comment]
Keep in mind, your csv should always contain one String field value.

**Comment by datasetutil** [comment]
How are you uploading the file? You can specify the delim in the json file. 


  "fileFormat" : {
    "charsetName" : "UTF-8",
    "fieldsDelimitedBy" : ",",
    "fieldsEnclosedBy" : "\"",
    "linesTerminatedBy" : "\n",
    "numberOfLinesToIgnore" : 1
  },.....

**Comment by ktokarski** [comment]
Today I have tried the other way. Firstly I have uploaded the dataset with 1 row only and have reviewed the Schema and updated it. Then I overwritten the whole data with full set and it is working without any errors.

Thanks for you support.
Ticket can be closed.
