### ISSUE TITLE
Dataset Utils App size on Mac

### ISSUE THREAD

**Issue by twoebkenberg** [forcedotcom/Analytics-Cloud-Dataset-Utils#12]
Just looked and my Dataset Utils app had ballooned to >30GB in size.  Not sure what is causing the size inflation, but can this be fixed?

**Comment by datasetutil** [comment]
Its because of all your csv and log files are archived in the directory relative to the app. I am going to move them out of the app directory and into <user> in next release. RIght now you can manually go and delete these files using finder

**Comment by datasetutil** [comment]
This is fixed in the latest release
