### ISSUE TITLE
No JSP support - error

### ISSUE THREAD

**Issue by asif-git** [forcedotcom/Analytics-Cloud-Dataset-Utils#13]
Hi,
I am getting following error highlighted in bold, when i run the bat file in a windows machine.
To resolve this, i also tried to include the jar file _org.eclipse.jetty.apache-jsp-9.3.8.v20160314_ in classpath but still it throws the same error.
Another fix i tried and failed was to pass option parameters _OPTIONS=server,jsp._

let me know if there is any fix for this plz. 

PS: the mac version of this utility works just fine.

*******************************************************************************
1 [main] INFO org.eclipse.jetty.util.log  - Logging initialized @662ms
warUrl:src/main/webapp
warUrlString:jar:file:/C:/Asif/Tools/datasetutils/datasetutils-32.0.27.jar!/login.html
warUrlString:jar:file:/C:/Asif/Tools/datasetutils/datasetutils-32.0.27.jar!/
284 [main] INFO org.eclipse.jetty.server.Server  - jetty-9.2.z-SNAPSHOT
**_## 56543 [main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor  - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet_**
74001 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.w.WebAppContext@1324409e{/,file:/C:/Users/inyabjk/AppData/Local/Temp/jetty-127.0.0.1-3174-datasetutils-32.0.27.jar-_-any-4601762413598751406.dir/we
bapp/,AVAILABLE}{jar:file:/C:/Asif/Tools/datasetutils/datasetutils-32.0.27.jar!/}
74351 [main] INFO org.eclipse.jetty.server.ServerConnector  - Started ServerConnector@51565ec2{HTTP/1.1}{127.0.0.1:3174}
74353 [main] INFO org.eclipse.jetty.server.Server  - Started @75027ms

Regards,
Asif

**Comment by asif-git** [comment]
@datasetutil let me know if there is any fix for this plz.

**Comment by datasetutil** [comment]
I build and run on windows machine with no issues so are customer far the past 8 months without any issue. probably something in your classpath is causing issue.

**Comment by asif-git** [comment]
@datasetutil Thanks. So setting the classpath correctly is the fix for this issue?
Have others reported it?
Please let me know if there are any other pointers. Thanks.

**Comment by asif-git** [comment]
Inspite of getting the error, the web ui still opens up at _http://127.0.0.1:3174/login.html_.
But after entering all creds, it shows an error : **_Stream ended unexpectedly_**

**Comment by datasetutil** [comment]
Thats a known issue with IE. use chrome or firefox or safari

**Comment by asif-git** [comment]
Great...It works in chrome. Thanks.
