### ISSUE TITLE
Getting 'Username may not be null' error

### ISSUE THREAD

**Issue by nehaarora1910** [forcedotcom/Analytics-Cloud-Dataset-Utils#14]
@datasetutil : Hi , I am getting a strange error while logging into my sandbox after running the dataset utils file. It says "username may not be null". And on clicking any of  the views like Dataflow list, dataset list etc. , I am not able to see anything.
Attached is the screenshot.
Please suggest if I am missing on anything.

![dataset utils error](https://cloud.githubusercontent.com/assets/15067879/14076238/a013e78a-f4fd-11e5-853e-4d39c92852bb.jpg)

Thanks.

**Comment by datasetutil** [comment]
When you login using the UI. Does your console show any errors? What browser are you using? Whats the URL you are providing?

**Comment by nehaarora1910** [comment]
When I ran the dataset utils jar file, it opens up in IE. It gives me error "stream ended unexpectedly" after I enter my sandbox credentials. So I used the same url "http://127.0.0.1:3174/dataflows.html" in Chrome browser.
In chrome, I was able to login but the home page shows this error attached in above screenshot. I checked the console, it is showing me this error: "http://127.0.0.1:3174/list?type=dataflow - Failed to load resource: the server responded with a status of 400 (Bad Request)"

**Comment by datasetutil** [comment]
can you try login into another instance? Do you have dev instance that you can test with? Just want to make sure it not related to some setting on the org?

**Comment by nehaarora1910** [comment]
@datasetutil : I tried with Dev instance also , but again getting same issue "Username may not be null".
Please help.

**Comment by datasetutil** [comment]
Sorry for the late response. By any chance do you have a proxy server in your network?

**Comment by nehaarora1910** [comment]
HI @datasetutil : i do not have proxy server.

**Comment by datasetutil** [comment]
I have release a new version. Can you please try using this version and if you still have issues copy and paste the console log and attach it here
