### ISSUE TITLE
decimalSeparator

### ISSUE THREAD

**Issue by troub** [forcedotcom/Analytics-Cloud-Dataset-Utils#15]
Hi, 

I'm having problems with the decimalSeperator.
It doesn't recognize it when I'm changing the decimalSeperator from "." to ",". 
(dot to comma)
It still uses the default "." as the default decimalSeperator.

Any idea how I can solve this issue?

Below the setting I'm using.

Thanks 
Troub

I get the following errormessage in the log
_Row {1} has error {java.lang.NumberFormatException: AMOUNT is not a valid number, value {320,460000000} : null}_
Here's the part of my .json File:

_, {
      "name" : "AMOUNT",
      "fullyQualifiedName" : "AMOUNT",
      "label" : "AMOUNT",
      "description" : "AMOUNT",
      "type" : "Numeric",
      "precision" : 18,
      "scale" : 9,
      "decimalSeparator" : ",",
      "defaultValue" : "0",
      "format" : null,
      "isSystemField" : false,
      "isUniqueId" : false,
      "isMultiValue" : false,
      "multiValueSeparator" : null,
      "fiscalMonthOffset" : 0,
      "firstDayOfWeek" : -1,
      "isYearEndFiscalYear" : true,
      "canTruncateValue" : true,
      "isSkipped" : false
}_

**Comment by datasetutil** [comment]
can you please share a few lines of your csv? please attach the csv and json file and I can then debug the issue

**Comment by krmyers2** [comment]
Was this ever resolved? I'm receiving the same error, but not related to the decimal separator (in my case I'm using a ".")
Sample Error: AMOUNT is not a valid number value {558.57} : Unparseable number: 558.57

**Comment by troub** [comment]
@krmyers2 
I found a workaround and wasn't following up anymore:
If you set the format in your json it should work.
In your case it would be "format" : "###.##",

I didn't check how the format line exactly is working but there's a good document where you can inform you. [https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data_format.pdf]()

Good Luck

**Comment by datasetutil** [comment]
You need to specify format only if your number is formatted. For example if you have a thousand separator you would have to specify a format.  A pure number with a decimal seperator "." does not require a format for parsing. All supported formats are listed here: https://github.com/forcedotcom/Analytics-Cloud-Dataset-Utils/wiki/FAQ#what-all-number-formats-are-supported

**Comment by krmyers2** [comment]
I'm confused..Isn't the format parameter only used for display of the number in the UI? It shouldn't have any influence on the ingestion of data right?

datasetutil, do you have any idea why I am receiving the invalid number message. I can upload the csv no problem using the native Wave upload facility (unfortunately that does not support anything other than OVERWRITE for some strange reason)

**Comment by krmyers2** [comment]
For anyone else with the same problem, where you need to define the format of your numeric value in the UI, You just need to specify that format in the Extended Metadata file (instead of the External Data Metadata file).

**Comment by datasetutil** [comment]
we use a different parser and therefore support formatted numbers, therefore your csv can contain a number value like $1,000.00, if you file does not contain formatted numbers, you should leave format null.

if you just want to specify format for UI display and not parsing you should use option --uploadformat=csv  this will ignore the format and load the csv as is. Make sure the number has no formatting in the input csv like $1,000.00 it should be  just 1000.00
