### ISSUE TITLE
java.net.SocketException

### ISSUE THREAD

**Issue by lchristel** [forcedotcom/Analytics-Cloud-Dataset-Utils#19]
I'm trying to use Dataset Utilities but get the following error when I try to login.  Does anyone know what this might mean?  I believe I have installed the correct java version:
H:\>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)
I'm using Firefox browser (44.0.2). 

Error:
160360 [qtp29531133-27] INFO org.apache.http.impl.client.DefaultHttpClient  - I/
O exception (java.net.SocketException) caught when connecting to {s}->https://lo
gin.salesforce.com:443: Connection reset
160361 [qtp29531133-27] INFO org.apache.http.impl.client.DefaultHttpClient  - Re
trying connect to {s}->https://login.salesforce.com:443

**Comment by datasetutil** [comment]
Can you share the entire console log

**Comment by lchristel** [comment]
Here is a complete log.  

C:\Users\lee\Downloads\Analytics-Cloud-Dataset-Utils-mast
-jar datasetutils-37.0.1.jar --server true
                *****************************************
                Salesforce Analytics Cloud Dataset Utils
                *****************************************
*********************************************************
java.version:1.8.0_101
java.class.path:datasetutils-37.0.1.jar
SystemClassLoader:/C:/Users/lee/Downloads/Analytics-Cloud
atasetutils37/datasetutils-37.0.1.jar
*********************************************************
DatsetUtils called with {2} Params:
{--server}:{true}
*********************************************************
0 [main] INFO org.eclipse.jetty.util.log  - Logging initi
warUrl:src/main/webapp
warUrlString:jar:file:/C:/Users/lee/Downloads/Analytics-C
er/datasetutils37/datasetutils-37.0.1.jar!/login.html
warUrlString:jar:file:/C:/Users/lee/Downloads/Analytics-C
er/datasetutils37/datasetutils-37.0.1.jar!/
1158 [main] INFO org.eclipse.jetty.server.Server  - jetty
51900 [main] INFO org.eclipse.jetty.webapp.StandardDescri
 Support for /, did not find org.eclipse.jetty.jsp.JettyJ
52271 [main] INFO org.eclipse.jetty.server.handler.Contex
.j.w.WebAppContext@b2c100{/,file:/C:/Users/lee/AppData/Lo
1-3174-datasetutils-37.0.1.jar-_-any-7030433380627471281.
jar:file:/C:/Users/lee/Downloads/Analytics-Cloud-Dataset-
ls37/datasetutils-37.0.1.jar!/}
53025 [main] INFO org.eclipse.jetty.server.ServerConnecto
ector@78c730{HTTP/1.1}{127.0.0.1:3174}
53029 [main] INFO org.eclipse.jetty.server.Server  - Star
137482 [qtp29531133-16] INFO org.apache.http.impl.client.
O exception (java.net.SocketException) caught when connec
gin.salesforce.com:443: Connection reset
137483 [qtp29531133-16] INFO org.apache.http.impl.client.
trying connect to {s}->https://login.salesforce.com:443
179988 [qtp29531133-17] INFO org.apache.http.impl.client.
O exception (java.net.SocketException) caught when connec
gin.salesforce.com:443: Connection reset
179989 [qtp29531133-17] INFO org.apache.http.impl.client.
trying connect to {s}->https://login.salesforce.com:443
197737 [qtp29531133-16] INFO org.apache.http.impl.client.
O exception (java.net.SocketException) caught when connec
gin.salesforce.com:443: Connection reset
197738 [qtp29531133-16] INFO org.apache.http.impl.client.
trying connect to {s}->https://login.salesforce.com:443

**Comment by datasetutil** [comment]
Do you have a proxy in your network?

**Comment by lchristel** [comment]
Not sure, I can ask my IT department.  But I did try to run the utilities from my laptop when at home without a VPN to our corporate network (i.e. just using my WiFi internet connection at home), and I got the same error.

**Comment by lchristel** [comment]
I note that I have been running the batch file:
java -jar datasetutils-37.0.1.jar --server true

When I run the batch file
@ECHO OFF
SET BASEDIR=%~dp0.
cd %BASEDIR%

FOR /F "delims=|" %%I IN ('DIR datasetutils*.jar /B /O:D') DO SET LATEST_JAR=%%I
echo %LATEST_JAR%

java -cp .;%LATEST_JAR% com.sforce.dataset.util.UpgradeChecker

FOR /F "delims=|" %%I IN ('DIR datasetutils*.jar /B /O:D') DO SET LATEST_JAR=%%I
echo %LATEST_JAR%

java -Xmx1G -jar %LATEST_JAR% --server true

I get the following log

datasetutils-37.0.1.jar
0 [main] INFO org.apache.http.impl.execch
t.SocketException) caught when processing
:443: Connection reset
12 [main] INFO org.apache.http.impl.execc
s}->https://api.github.com:443

**Comment by datasetutil** [comment]
maybe the firewall is on your laptop and not the network

**Comment by lchristel** [comment]
We use Symantec Endpoint Protection.  Could that be blocking it?

https://cloud.githubusercontent.com/assets/20820821/18293135/d5c9ac26-7445-11e6-9660-cec0612f405d.png

**Comment by datasetutil** [comment]
Yup! thats it

**Comment by lchristel** [comment]
What do I need to ask our IT department to do?  I cannot turn the antivirus software off.
Thanks,

**Comment by datasetutil** [comment]
you dont need to disable the firewall. Just add a bypass rule to allow this process to connect to the internet specifically salesforce.com, I cant comment on the steps to do that. Maybe google can help: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=allow+application+rule+symantec+endpoint
