### ISSUE TITLE
Question on CPU Utilization

### ISSUE THREAD

**Issue by arvindaiah** [forcedotcom/Analytics-Cloud-Dataset-Utils#22]
Hi,

This tool is really good and we are trying to automate some data loads using the tool.

We have created a batch file with ability to pick files and load it into Wave. We have some of these batch files running in parallel and loading data to different datasets. One thing we have noticed is that tools seems to utilize only one CPU and slows down significantly when loading large datasets. Is one CPU utilization by design or something that can be improved upon?

Thanks,
Arvind

**Comment by datasetutil** [comment]
Are you using the batch interface (command line) or UI? If you are starting multiple processes and its still CPU usage is not not high then you are blocked in IO. Get a faster disk
