### ISSUE TITLE
Unable to Specify Schema on initial load through console mode

### ISSUE THREAD

**Issue by Manojdanthala** [forcedotcom/Analytics-Cloud-Dataset-Utils#23]
Hi,
I have the following issue:
In our case, we have some numeric columns and some text columns in CSV file. We need to consider all columns as text in the schema without giving numeric values with quotes. But Everytime when we overwrite the fresh data its chaging the schema. Is there any possibility to specify Schema file(JSON) while uploading through console mode?

Thanks,

**Comment by datasetutil** [comment]
if the input file is  file.csv then the jar will look for a schema file file_schema.json in the same directory as input file. If the file exists it will use it and not generate a new one.
