### ISSUE TITLE
XMD failed validation error

### ISSUE THREAD

**Issue by grjkz** [forcedotcom/Analytics-Cloud-Dataset-Utils#28]
Hello everyone,

I am receiving this email from salesforce when I attempt to upload/import Opportunity records to WAVE Analytics. I don't know how to fix this. 

~~The data completely fails to upload to WAVE but the CLI output says there are no errors, only (74k) successes and "Succesfully uploaded [file.csv] to Dataset (Opportunity) uploadTime ([time]) msecs".~~
Looks like the data was uploaded into WAVE after all. There was another data set with the same exact name which was being overwritten in an entirely different folder.

> Dear User
> 
> You are receiving this email because one or more datasets has an XMD file that has failed validation. Please see the list of errors below.
> 
> Opportunity
> Found Measures in User XMD which are not present in System XMD: [Account.Corporate.Current_Monthly_Revenue_USD__c, Trial_Started__c_day_epoch, Last_Modified_by_Sales__c_day_epoch, Total_Of_Opp_Revenue__c, Account.CreatedDate_day_epoch, Demo_Completed__c_s
> 
> The recommended next step is to review the XMD file and address the errors. For more information on accessing the XMD and addressing issues, please see the link to the KB below:
> 
> https://help.salesforce.com/apex/HTViewSolution?urlname=XMD-1-1-to-2-0-Transition

**Comment by Mahaarajan** [comment]
Did you resolve this issue? I too am facing a similar problem. Any solution/help would be appreciated.
