### ISSUE TITLE
Date format derivation from CSV input file

### ISSUE THREAD

**Issue by dhusband** [forcedotcom/Analytics-Cloud-Dataset-Utils#3]
The date format is defaulting to yyyy/MM/dd when the source data is dd/MM/yyyy or MM/dd/yyyy. This was not happening with my previous version of the utility. If there is a specific date format expected, or if there is a way of specifying the date format can this be added to the wiki? I know this can be changed in the generated JSON, but would be better if didn't have to.

**Comment by datasetutil** [comment]
I will investigate, although its technically not possible to pick a wrong format. Are you checking the date format in excel? cause excel will not show the date in the formats that actually exist in the raw file

**Comment by dhusband** [comment]
Thanks for the response. I'm not using Excel. This used to work ok. See below for CSV sample rows and then snippets from the JSON schemas generated by v.32.0.9 and older version of datasetutils... showing a different date format interpretation.

//---Sample data from CSV---------------------------------------------------------
Type,Date,Units,Company,Brand,Reason
Sales,07/30/2014,24,Coca Cola,Fanta,None
Sales,09/30/2014,48,Coca Cola,Fanta,None
Sales,07/30/2014,24,Coca Cola,Fanta,None

//---Snippet from JSON Schema generated by datasetutils-32.0.9-------
      "name" : "Date",
      "fullyQualifiedName" : "Date",
      "label" : "Date",
      "description" : "Date",
      "type" : "Date",
      "precision" : 0,
      "scale" : 0,
      "defaultValue" : "",
      "format" : "yyyy/MM/dd",
      "isSystemField" : false,
      "isUniqueId" : false,
      "isMultiValue" : false,
      "multiValueSeparator" : null,
      "fiscalMonthOffset" : 0,
      "firstDayOfWeek" : -1,
      "isYearEndFiscalYear" : true,
      "isSkipped" : false,
      "decimalSeparator" : ".",
      "sortIndex" : 0,
      "isSortAscending" : true,
      "isComputedField" : false,
      "computedFieldExpression" : null
    },

//---Snippet from JSON Schema generated by old datasetutils-------
      "name" : "Date",
      "fullyQualifiedName" : "Date",
      "label" : "Date",
      "description" : "Date",
      "type" : "Date",
      "precision" : 0,
      "scale" : 0,
      "defaultValue" : "",
      "format" : "MM/dd/yyyy",
      "isSystemField" : false,
      "isUniqueId" : false,
      "isMultiValue" : false,
      "multiValueSeparator" : null,
      "fiscalMonthOffset" : 0,
      "multiValueSeperator" : null
    },

//-------------------------------------------------------------------

**Comment by datasetutil** [comment]
I ran your csv sample above and it correctly detected the date format. see sample output below:
*******************************************************************************
Detecting schema from csv file {C:\Users\pgupta\Downloads\date_test.csv} ...
Column: Type, Type: Text, Precison: 5
Column: Date, Type: Date, Format: MM/d/yyyy
Column: Units, Type: Numeric, Scale: 0
Column: Company, Type: Text, Precison: 9
Column: Brand, Type: Text, Precison: 5
Column: Reason, Type: Text, Precison: 4
Schema file {C:\Users\pgupta\Downloads\date_test_schema.json} successfully generated...
*******************************************************************************

**Comment by dhusband** [comment]
Hi. Thanks for trying it on your side. I just loaded it again on my side... different result to yours:
//-----------------------------------
Command:
java -jar datasetutils-32.0.9.jar --action load --u dhusband@winter15.analytics --p S@@@force1 --inputFile CocaCola.csv --dataset Laboratory
//-----------------------------------
Result
Detecting schema from csv file {CocaCola.csv} ...
Column: Type, Type: Text, Precison: 5
Column: Date, Type: Date, Format: yyyy/MM/dd
Column: Units, Type: Numeric, Scale: 0
Column: Company, Type: Text, Precison: 9
Column: Brand, Type: Text, Precison: 5
Column: Reason, Type: Text, Precison: 4
Schema file {CocaCola_schema.json} successfully generated...
//-----------------------------------
Does the Java utility use my locale? Why might it perform differently to yours? I'm using a Mac. 

The reason it is important is I'm creating a data creation utility  for use by a wide group of people. I don't want to require the users to edit JSON files. If I know how the java utility is detecting the date format I can make my utility generate the CSV accordingly. Note that my colleague also encountered this behaviour when loading a CSV.

**Comment by datasetutil** [comment]
I am at a loss. I and everyone else here uses a mac too. The code for detecting type is here in guthub. You are free to look at the code

**Comment by datasetutil** [comment]
I just made some code changes and uploaded a new release. Since I cant replicate your issue. can you try at your end with the latest version

**Comment by dhusband** [comment]
That seems to work! Thank you... I had just looked through and identified getSuportedDateFormats() as the possible problem area as not able to load anything successfully prior to 32.0.2... I'll load some more data and ensure it behaves as expected.
