### ISSUE TITLE
Load function not handling latitude & Longitude values. 

### ISSUE THREAD

**Issue by esandoval30** [forcedotcom/Analytics-Cloud-Dataset-Utils#5]
When loading a csv file containing two columns representing latitude and longitud values. With values entered as long decimals (with different number of decimals), the Load function throws a Java exception

The file contains rows as follows
id, latitude, longitude, name
33,41.877181, -87.627844, stop1
34,41.88457623, -87.63188991, stop2

The exception is java.lang.ArithmeticException: Rounding necessary

Both columns were detected as numeric but ideally, these should be recognised as dimensions (or at least a special kind of dimension - e.g. a geolocation dimension)...once the engine support geo location data

**Comment by datasetutil** [comment]
How can you tell 41.877181 or 41.87 or 41.8771811234 is a latitude and not a number?

**Comment by tbacewicz** [comment]
Also, why don't you just change it to a dimension in the schema and reload the csv @esandoval30 ?
