### ISSUE TITLE
UI Login has to have security token?

### ISSUE THREAD

**Issue by mdhari** [forcedotcom/Analytics-Cloud-Dataset-Utils#7]
Was trying to login to an environment that is publicly available through server mode but was getting this error message:

[LoginFault [ApiFault exceptionCode='LOGIN_MUST_USE_SECURITY_TOKEN' exceptionMessage='Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To receive a new security token, log in to salesforce.com at http://login.salesforce.com and click Setup | My Personal Information | Reset Security Token.' ] ]

Strangely, I was able to login through interactive mode just fine. Any ideas why?

**Comment by datasetutil** [comment]
1. First get your security token: To receive a new security token, log in to salesforce.com at http://login.salesforce.com and click Setup | My Personal Information | Reset Security Token.

2. in the password field enter password + token for example if the password is '1234' and token is 'token' then enter: 1234token
