### ISSUE TITLE
XMD not downloading on Windows Box

### ISSUE THREAD

**Issue by mdhari** [forcedotcom/Analytics-Cloud-Dataset-Utils#8]
For some reason the XMD is not downloading into the XMD editor when I use a Windows box. Works fine on my Mac. Using version 32.0.25 on both machines. Any ideas?

**Comment by datasetutil** [comment]
Can you share you logs

**Comment by mdhari** [comment]
How strange, there is no Org folder generated or a log file.

**Comment by datasetutil** [comment]
Then its a perm issue related to being able to write to the directory

**Comment by datasetutil** [comment]
closing- no response
